# Generated by Django 5.1 on 2025-04-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_earned', models.DateField()),
                ('credential_link', models.URLField(blank=True)),
            ],
        ),
    ]
