# Generated by Django 5.1 on 2025-04-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='date_earned',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
    ]
